image: rust:1.37

stages:
  - check
  - build
  - document
  - check_artifacts
  - publish
  - pages

check:
  stage: check
  script: 
    - cargo build
    - cargo test
  only: 
    - master
    - merge_requests
  
build:
  stage: build 
  script: cargo build --release
  only: 
  - master
  - merge_requests
  artifacts:
    paths: 
    - target/release/nodespeak
    expire_in: 30 minutes
  
document:
  stage: document
  image: rustlang/rust:nightly
  script: cargo doc
  only: 
  - master
  - merge_requests
  artifacts:
    paths:
    - target/doc
    expire_in: 30 minutes

check_artifacts:
  stage: check_artifacts
  image: alpine
  dependencies: 
  - build
  - document
  script: 
  - test -e target/release/nodespeak
  - test -e target/doc
  only:
  - merge_requests

publish:
  stage: publish
  image: alpine
  dependencies: 
  - build
  - document
  script: 
  - mv target/release/nodespeak nodespeak
  - mv target/doc pages
  only: 
  - master
  artifacts:
    paths:
    - nodespeak
    - pages

pages:
  stage: pages 
  image: alpine
  dependencies:
  - publish
  script:
  - mv pages public
  only: 
  - master
  artifacts:
    paths:
    - public
