image: alpine

stages:
  - check
  - build
  - document
  - check_artifacts
  - publish
  - pages

check:
  stage: check
  # LLVM takes longer to build / install than Rust. Use a LLVM image then put Rust on top of it.
  image: klee/llvm:100_O_D_A_ubuntu_bionic-20200112
  script: 
    - ls /
    - ls /lib
    - ls /root
    - ls /home/*
    - apt-get update
    - apt-get -y install curl build-essential
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source $HOME/.cargo/env
    - cargo test
  only: 
    - master
    - merge_requests
  
build:
  stage: build 
  image: klee/llvm:100_O_D_A_ubuntu_bionic-20200112
  script: 
    - apt-get update
    - apt-get -y install curl build-essential
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source $HOME/.cargo/env
    - cargo build --release
  only: 
  - master
  - merge_requests
  artifacts:
    paths: 
    - target/release/nodespeak
    expire_in: 30 minutes
  
document:
  stage: document
  image: rustlang/rust:nightly
  script: cargo doc
  only: 
  - master
  - merge_requests
  artifacts:
    paths:
    - target/doc
    expire_in: 30 minutes

check_artifacts:
  stage: check_artifacts
  dependencies: 
  - build
  - document
  script: 
  - test -e target/release/nodespeak
  - test -e target/doc
  only:
  - merge_requests

publish:
  stage: publish
  dependencies: 
  - build
  - document
  script: 
  - mv target/release/nodespeak nodespeak
  - mv target/doc pages
  only: 
  - master
  artifacts:
    paths:
    - nodespeak
    - pages

pages:
  stage: pages 
  dependencies:
  - publish
  script:
  - mv pages public
  only: 
  - master
  artifacts:
    paths:
    - public
