image: gcc:7.3
before_script:
  - apt update -qq && apt install -y make libboost-system-dev
  - wget https://github.com/Kitware/CMake/releases/download/v3.13.0/cmake-3.13.0-Linux-x86_64.sh
  - chmod +x cmake-3.13.0-Linux-x86_64.sh
  - ./cmake-3.13.0-Linux-x86_64.sh --skip-license

build:
  stage: "build"
  artifacts:
    paths:
      - build/waveguide*
      - build/libwaveguide*
  script:
    - mkdir build
    - cd build
    - ../bin/cmake ..
    - make

test:
  stage: "test"
  dependencies:
    - build
  script:
    - cd build
    - ./waveguide_test_runner
