image: gcc:7.3
before_script:
  - apt update -qq && apt install -y make cmake libboost-system-dev

build:
  stage: "build"
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
  stage: "test"
  script:
    - cd build
    - ./waveguide_test_runner
