[package]
name = "waveguide"
version = "0.0.0"
authors = ["Code_Cube <Code_Cube@gitlab.com>"]
edition = "2018"

[dependencies]
colored = "1.8"
pest = "2.1.1"
pest_derive = "2.1.0"
readonly = "0.1.5"
terminal_size="0.1.8"
