[package]
name = "nodespeak"
version = "0.0.0"
authors = ["Code_Cube <Code_Cube@gitlab.com>"]
edition = "2018"
default-run="nodespeak"

[features]
no-vague=["no-resolved"]
no-resolved=["no-trivial"]
no-trivial=["no-llvmir"]
no-llvmir=[]

[dependencies]
colored = "1.8"
libc = "0.2"
llvm-sys = "100"
num_enum = "0.4"
pest = "2.1"
pest_derive = "2.1"
readonly = "0.1"
terminal_size="0.1"
text_io = "0.1"
