[package]
name = "waveguide"
version = "0.0.0"
authors = ["Code_Cube <Code_Cube@gitlab.com>"]
edition = "2018"

[dependencies]
colored = "1.8"
libc = "0.2"
pest = "2.1"
pest_derive = "2.1"
readonly = "0.1"
terminal_size="0.1"
text_io = "0.1"
